// PrivacySections.tsx
export const Section1 = () => (<section id="section1"><h2><span className="section-number">1</span>What Information Do We Collect?</h2><h3>Information You Provide Directly</h3><p><strong>In Short:</strong> We collect personal information that you voluntarily provide to us.</p><p>We collect personal information that you voluntarily provide when you express an interest in obtaining information about us or our products and Services, when you participate in activities on the Services, or when you contact us directly.</p></section>);
export const Section2 = () => (<section id="section2"><h2><span className="section-number">2</span>How Do We Process Your Information?</h2><p><strong>In Short:</strong> We process your information for various business purposes listed below. We may also process your information for other purposes only with your prior explicit consent.</p></section>);
export const Section3 = () => (<section id="section3"><h2><span className="section-number">3</span>What Legal Bases Do We Rely On?</h2><p><strong>In Short:</strong> We only process your personal information when we have a valid legal reason to do so under applicable law.</p></section>);
export const Section4 = () => (<section id="section4"><h2><span className="section-number">4</span>When and With Whom Do We Share Your Information?</h2><p><strong>In Short:</strong> We share information in specific situations and only with necessary third parties.</p></section>);
export const Section5 = () => (<section id="section5"><h2><span className="section-number">5</span>Cookies and Tracking Technologies</h2><p><strong>In Short:</strong> We use cookies and similar tracking technologies to enhance your experience and analyze our Services.</p></section>);
export const Section6 = () => (<section id="section6"><h2><span className="section-number">6</span>Is Your Information Transferred Internationally?</h2><p><strong>In Short:</strong> Your information may be transferred, stored, and processed in countries other than your own.</p></section>);
export const Section7 = () => (<section id="section7"><h2><span className="section-number">7</span>How Long Do We Keep Your Information?</h2><p><strong>In Short:</strong> We keep your information only as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless legally required to retain it longer.</p></section>);
export const Section8 = () => (<section id="section8"><h2><span className="section-number">8</span>How Do We Keep Your Information Safe?</h2><p><strong>In Short:</strong> We use organizational and technical security measures designed to protect your personal information.</p></section>);
export const Section9 = () => (<section id="section9"><h2><span className="section-number">9</span>Do We Collect Information From Minors?</h2><p><strong>In Short:</strong> We do not knowingly collect data from children under 18 years of age.</p></section>);
export const Section10 = () => (<section id="section10"><h2><span className="section-number">10</span>What Are Your Privacy Rights?</h2><p><strong>In Short:</strong> Depending on your location, you have certain rights regarding your personal information.</p></section>);
export const Section11 = () => (<section id="section11"><h2><span className="section-number">11</span>Controls For Do-Not-Track Features</h2><p><strong>In Short:</strong> Most browsers include a Do-Not-Track feature, but we do not currently respond to these signals as there is no industry standard.</p></section>);
export const Section12 = () => (<section id="section12"><h2><span className="section-number">12</span>US Residents' Specific Privacy Rights</h2><p><strong>In Short:</strong> Residents of certain US states have specific privacy rights regarding their personal information.</p></section>);
export const Section13 = () => (<section id="section13"><h2><span className="section-number">13</span>Email Communications and Marketing</h2><p><strong>In Short:</strong> We'll only send you marketing emails if you've opted in, and we provide easy ways to unsubscribe.</p></section>);
export const Section14 = () => (<section id="section14"><h2><span className="section-number">14</span>Third-Party Links and Services</h2><p><strong>In Short:</strong> Our Services may contain links to third-party websites and services that have their own privacy policies.</p></section>);
export const Section15 = () => (<section id="section15"><h2><span className="section-number">15</span>Do We Make Updates to This Notice?</h2><p><strong>In Short:</strong> Yes, we'll update this Privacy Policy as needed to comply with laws and reflect our practices.</p></section>);
export const Section16 = () => (<section id="section16"><h2><span className="section-number">16</span>How Can You Contact Us About This Notice?</h2><p>If you have questions, concerns, or requests related to this Privacy Policy or our privacy practices, please contact us at habitprosupport@gmail.com.</p></section>);
export const Section17 = () => (<section id="section17"><h2><span className="section-number">17</span>How to Review, Update, or Delete Your Data</h2><p><strong>In Short:</strong> You have the right to access, update, and delete your personal information.</p></section>);